[package]
name = "WebServer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
tokio = "1.36.0"
shuttle-rocket = "0.41.0"
shuttle-runtime = "0.41.0"